import type { StoLaborCatalogItem } from "./sto-labor-catalog";

/** Полный каталог работ СТО (легковые + универсальные услуги) */
export const STO_LABOR_CATALOG_FULL: StoLaborCatalogItem[] = [
  // ── ТО ──────────────────────────────────────────────────────────────────────
  { code: "TO-100", name: "ТО-1 (масло двигателя + масляный фильтр)", normHours: 1.0, category: "ТО" },
  { code: "TO-150", name: "ТО-1 расширенное (+ воздушный фильтр)", normHours: 1.2, category: "ТО" },
  { code: "TO-200", name: "ТО-2 (масло, фильтры, свечи, жидкости)", normHours: 2.5, category: "ТО" },
  { code: "TO-300", name: "ТО-3 (полное: ремни, тормозная, охлаждение)", normHours: 4.0, category: "ТО" },
  { code: "TO-OIL", name: "Замена моторного масла", normHours: 0.6, category: "ТО" },
  { code: "TO-OIL-F", name: "Замена масляного фильтра", normHours: 0.3, category: "ТО" },
  { code: "TO-AIR-F", name: "Замена воздушного фильтра", normHours: 0.3, category: "ТО" },
  { code: "TO-CAB-F", name: "Замена салонного фильтра", normHours: 0.4, category: "ТО" },
  { code: "TO-FUEL-F", name: "Замена топливного фильтра", normHours: 0.8, category: "ТО" },
  { code: "TO-SPARK", name: "Замена свечей зажигания (комплект)", normHours: 0.8, category: "ТО" },
  { code: "TO-BRK-FL", name: "Замена тормозной жидкости", normHours: 0.8, category: "ТО" },
  { code: "TO-COOL", name: "Замена охлаждающей жидкости", normHours: 1.0, category: "ТО" },
  { code: "TO-ATF", name: "Замена масла АКПП (частичная)", normHours: 1.2, category: "ТО" },
  { code: "TO-GEAR", name: "Замена масла МКПП / редуктора", normHours: 1.0, category: "ТО" },
  { code: "TO-WIPER", name: "Замена щёток стеклоочистителя", normHours: 0.2, category: "ТО" },
  { code: "TO-INSPECT", name: "Предпродажный осмотр", normHours: 1.5, category: "ТО" },
  { code: "TO-SEASON", name: "Сезонное ТО (осмотр + жидкости)", normHours: 1.5, category: "ТО" },

  // ── Диагностика ─────────────────────────────────────────────────────────────
  { code: "DIAG", name: "Компьютерная диагностика", normHours: 0.8, category: "Диагностика" },
  { code: "DIAG-ENG", name: "Диагностика двигателя", normHours: 1.5, category: "Диагностика" },
  { code: "DIAG-AT", name: "Диагностика АКПП", normHours: 1.5, category: "Диагностика" },
  { code: "DIAG-ABS", name: "Диагностика ABS / ESP", normHours: 1.0, category: "Диагностика" },
  { code: "DIAG-AIR", name: "Диагностика подушек безопасности", normHours: 1.0, category: "Диагностика" },
  { code: "DIAG-AC", name: "Диагностика кондиционера", normHours: 1.0, category: "Диагностика" },
  { code: "DIAG-ELEC", name: "Диагностика электрооборудования", normHours: 1.5, category: "Диагностика" },
  { code: "DIAG-SUSP", name: "Диагностика подвески (стенд / осмотр)", normHours: 0.8, category: "Диагностика" },
  { code: "DIAG-BRK", name: "Диагностика тормозной системы", normHours: 0.6, category: "Диагностика" },
  { code: "DIAG-LEAK", name: "Поиск утечек (дымогенератор / УФ)", normHours: 1.5, category: "Диагностика" },
  { code: "DIAG-NOISE", name: "Поиск посторонних шумов", normHours: 1.0, category: "Диагностика" },
  { code: "DIAG-SMOKE", name: "Дымомер / проверка выхлопа", normHours: 0.5, category: "Диагностика" },
  { code: "DIAG-CLEAR", name: "Сброс ошибок ЭБУ", normHours: 0.3, category: "Диагностика" },
  { code: "DIAG-ADAS", name: "Калибровка ADAS / камер", normHours: 2.0, category: "Диагностика" },

  // ── Двигатель ───────────────────────────────────────────────────────────────
  { code: "ENG-BELT", name: "Замена ремня ГРМ", normHours: 4.0, category: "Двигатель" },
  { code: "ENG-BELT-K", name: "Замена ремня ГРМ + ролики + помпа", normHours: 5.5, category: "Двигатель" },
  { code: "ENG-CHAIN", name: "Замена цепи ГРМ", normHours: 8.0, category: "Двигатель" },
  { code: "ENG-PUMP", name: "Замена помпы охлаждения", normHours: 3.0, category: "Двигатель" },
  { code: "ENG-THERM", name: "Замена термостата", normHours: 1.5, category: "Двигатель" },
  { code: "ENG-RAD", name: "Замена радиатора охлаждения", normHours: 2.5, category: "Двигатель" },
  { code: "ENG-RAD-H", name: "Замена радиатора печки", normHours: 4.0, category: "Двигатель" },
  { code: "ENG-FAN", name: "Замена вентилятора охлаждения", normHours: 1.5, category: "Двигатель" },
  { code: "ENG-SPARK", name: "Замена свечей зажигания", normHours: 0.8, category: "Двигатель" },
  { code: "ENG-COIL", name: "Замена катушки зажигания (1 шт.)", normHours: 0.5, category: "Двигатель" },
  { code: "ENG-COIL-4", name: "Замена катушек зажигания (комплект)", normHours: 1.2, category: "Двигатель" },
  { code: "ENG-WIRE", name: "Замена высоковольтных проводов", normHours: 0.8, category: "Двигатель" },
  { code: "ENG-INJ", name: "Замена форсунки (1 шт.)", normHours: 1.5, category: "Двигатель" },
  { code: "ENG-INJ-W", name: "Промывка форсунок (стенд)", normHours: 2.0, category: "Двигатель" },
  { code: "ENG-INJ-U", name: "Ультразвуковая чистка форсунок", normHours: 3.0, category: "Двигатель" },
  { code: "ENG-TB", name: "Чистка дроссельной заслонки", normHours: 0.8, category: "Двигатель" },
  { code: "ENG-EGR", name: "Чистка / замена клапана EGR", normHours: 2.5, category: "Двигатель" },
  { code: "ENG-DPF", name: "Регенерация / чистка сажевого фильтра", normHours: 2.0, category: "Двигатель" },
  { code: "ENG-TURBO", name: "Замена турбины", normHours: 6.0, category: "Двигатель" },
  { code: "ENG-HEAD-G", name: "Замена прокладки ГБЦ", normHours: 12.0, category: "Двигатель" },
  { code: "ENG-VALVE", name: "Регулировка клапанов", normHours: 2.5, category: "Двигатель" },
  { code: "ENG-MOUNT", name: "Замена опоры двигателя (1 шт.)", normHours: 1.5, category: "Двигатель" },
  { code: "ENG-OIL-SEAL", name: "Замена сальника коленвала (передний)", normHours: 3.0, category: "Двигатель" },
  { code: "ENG-COMP", name: "Замер компрессии", normHours: 1.0, category: "Двигатель" },
  { code: "ENG-DECARB", name: "Декарбонизация двигателя", normHours: 1.5, category: "Двигатель" },
  { code: "ENG-FLUSH", name: "Промывка масляной системы", normHours: 0.5, category: "Двигатель" },
  { code: "ENG-OVERHAUL", name: "Капитальный ремонт двигателя", normHours: 40.0, category: "Двигатель" },
  { code: "ENG-REMOVE", name: "Снятие / установка двигателя", normHours: 16.0, category: "Двигатель" },

  // ── Тормоза ─────────────────────────────────────────────────────────────────
  { code: "BRK-PAD-F", name: "Замена передних колодок", normHours: 1.0, category: "Тормоза" },
  { code: "BRK-PAD-R", name: "Замена задних колодок", normHours: 1.2, category: "Тормоза" },
  { code: "BRK-DISC-F", name: "Замена передних тормозных дисков", normHours: 1.5, category: "Тормоза" },
  { code: "BRK-DISC-R", name: "Замена задних тормозных дисков", normHours: 1.8, category: "Тормоза" },
  { code: "BRK-DISC-PAD-F", name: "Замена передних дисков + колодки", normHours: 1.8, category: "Тормоза" },
  { code: "BRK-DISC-PAD-R", name: "Замена задних дисков + колодки", normHours: 2.0, category: "Тормоза" },
  { code: "BRK-DRUM", name: "Замена задних тормозных колодок (барабан)", normHours: 2.0, category: "Тормоза" },
  { code: "BRK-DRUM-R", name: "Замена / проточка барабанов", normHours: 2.5, category: "Тормоза" },
  { code: "BRK-CAL-F", name: "Замена переднего суппорта", normHours: 1.5, category: "Тормоза" },
  { code: "BRK-CAL-R", name: "Замена заднего суппорта", normHours: 1.5, category: "Тормоза" },
  { code: "BRK-CAL-REP", name: "Ремонт суппорта (переборка)", normHours: 2.0, category: "Тормоза" },
  { code: "BRK-HOSE", name: "Замена тормозного шланга", normHours: 0.8, category: "Тормоза" },
  { code: "BRK-PIPE", name: "Замена тормозной трубки", normHours: 1.5, category: "Тормоза" },
  { code: "BRK-MASTER", name: "Замена главного тормозного цилиндра", normHours: 2.0, category: "Тормоза" },
  { code: "BRK-BOOST", name: "Замена вакуумного усилителя", normHours: 2.5, category: "Тормоза" },
  { code: "BRK-HAND", name: "Регулировка / ремонт ручника", normHours: 1.0, category: "Тормоза" },
  { code: "BRK-HAND-CAB", name: "Замена троса ручного тормоза", normHours: 1.5, category: "Тормоза" },
  { code: "BRK-ABS-PUMP", name: "Замена блока ABS", normHours: 2.5, category: "Тормоза" },
  { code: "BRK-BLEED", name: "Прокачка тормозной системы", normHours: 0.8, category: "Тормоза" },
  { code: "BRK-LATHE", name: "Проточка тормозных дисков (ось)", normHours: 1.0, category: "Тормоза" },

  // ── Подвеска ────────────────────────────────────────────────────────────────
  { code: "SUSP-BALL", name: "Замена шаровой опоры (1 сторона)", normHours: 1.5, category: "Подвеска" },
  { code: "SUSP-BALL-2", name: "Замена шаровых опор (пара)", normHours: 2.5, category: "Подвеска" },
  { code: "SUSP-STRUT-F", name: "Замена переднего амортизатора (1 сторона)", normHours: 2.0, category: "Подвеска" },
  { code: "SUSP-STRUT-R", name: "Замена заднего амортизатора (1 сторона)", normHours: 1.5, category: "Подвеска" },
  { code: "SUSP-STRUT-4", name: "Замена амортизаторов (комплект 4 шт.)", normHours: 5.0, category: "Подвеска" },
  { code: "SUSP-SPRING", name: "Замена пружины подвески (1 шт.)", normHours: 2.0, category: "Подвеска" },
  { code: "SUSP-LINK", name: "Замена стойки стабилизатора", normHours: 0.6, category: "Подвеска" },
  { code: "SUSP-LINK-2", name: "Замена стоек стабилизатора (пара)", normHours: 1.0, category: "Подвеска" },
  { code: "SUSP-BUSH", name: "Замена сайлентблоков (1 узел)", normHours: 2.5, category: "Подвеска" },
  { code: "SUSP-ARM-F", name: "Замена переднего рычага", normHours: 2.0, category: "Подвеска" },
  { code: "SUSP-ARM-R", name: "Замена заднего рычага", normHours: 2.0, category: "Подвеска" },
  { code: "SUSP-HUB-F", name: "Замена ступицы передняя", normHours: 2.5, category: "Подвеска" },
  { code: "SUSP-HUB-R", name: "Замена ступицы задняя", normHours: 2.0, category: "Подвеска" },
  { code: "SUSP-BEAR-F", name: "Замена подшипника ступицы передний", normHours: 2.5, category: "Подвеска" },
  { code: "SUSP-BEAR-R", name: "Замена подшипника ступицы задний", normHours: 2.0, category: "Подвеска" },
  { code: "SUSP-PAD", name: "Замена опорного подшипника амортизатора", normHours: 2.5, category: "Подвеска" },
  { code: "SUSP-SUBF", name: "Замена подрамника", normHours: 8.0, category: "Подвеска" },
  { code: "SUSP-LEAF", name: "Замена рессоры (грузовая / УАЗ)", normHours: 3.0, category: "Подвеска" },
  { code: "SUSP-PNEU", name: "Ремонт пневмоподвески", normHours: 3.0, category: "Подвеска" },
  { code: "SUSP-ALIGN-CHECK", name: "Проверка углов установки колёс", normHours: 0.5, category: "Подвеска" },

  // ── Рулевое ───────────────────────────────────────────────────────────────────
  { code: "STEER-END", name: "Замена рулевого наконечника", normHours: 1.0, category: "Рулевое" },
  { code: "STEER-TIE", name: "Замена рулевой тяги", normHours: 1.2, category: "Рулевое" },
  { code: "STEER-RACK", name: "Замена рулевой рейки", normHours: 5.0, category: "Рулевое" },
  { code: "STEER-RACK-REP", name: "Ремонт рулевой рейки", normHours: 6.0, category: "Рулевое" },
  { code: "STEER-PUMP", name: "Замена насоса ГУР", normHours: 2.5, category: "Рулевое" },
  { code: "STEER-FLUID", name: "Замена жидкости ГУР / ЭУР", normHours: 0.8, category: "Рулевое" },
  { code: "STEER-COL", name: "Замена рулевого вала / кардана", normHours: 2.0, category: "Рулевое" },
  { code: "STEER-BOX", name: "Замена рулевого редуктора (груз.)", normHours: 6.0, category: "Рулевое" },
  { code: "STEER-ADJ", name: "Регулировка развал-схождения (рулевое)", normHours: 1.0, category: "Рулевое" },

  // ── Трансмиссия ───────────────────────────────────────────────────────────────
  { code: "TRN-ATF", name: "Замена масла АКПП", normHours: 1.5, category: "Трансмиссия" },
  { code: "TRN-ATF-FULL", name: "Полная замена масла АКПП (аппарат)", normHours: 2.5, category: "Трансмиссия" },
  { code: "TRN-ATF-FILT", name: "Замена фильтра АКПП", normHours: 3.0, category: "Трансмиссия" },
  { code: "TRN-GEAR", name: "Замена масла МКПП", normHours: 1.0, category: "Трансмиссия" },
  { code: "TRN-CVT", name: "Замена масла вариатора", normHours: 2.0, category: "Трансмиссия" },
  { code: "TRN-DIFF", name: "Замена масла дифференциала", normHours: 0.8, category: "Трансмиссия" },
  { code: "TRN-TCASE", name: "Замена масла раздаточной коробки", normHours: 1.0, category: "Трансмиссия" },
  { code: "TRN-AXLE", name: "Замена масла в мостах (4x4)", normHours: 1.2, category: "Трансмиссия" },
  { code: "TRN-CV-IN", name: "Замена внутреннего ШРУСа", normHours: 2.5, category: "Трансмиссия" },
  { code: "TRN-CV-OUT", name: "Замена наружного ШРУСа", normHours: 2.0, category: "Трансмиссия" },
  { code: "TRN-CV-BOOT", name: "Замена пыльника ШРУСа", normHours: 2.0, category: "Трансмиссия" },
  { code: "TRN-DRIVESHAFT", name: "Замена карданного вала", normHours: 2.5, category: "Трансмиссия" },
  { code: "TRN-CROSS", name: "Замена крестовины кардана", normHours: 2.0, category: "Трансмиссия" },
  { code: "TRN-FLYWHEEL", name: "Замена маховика", normHours: 8.0, category: "Трансмиссия" },
  { code: "TRN-GEAR-REP", name: "Ремонт МКПП", normHours: 16.0, category: "Трансмиссия" },
  { code: "TRN-AT-REP", name: "Ремонт АКПП (снятие / установка)", normHours: 12.0, category: "Трансмиссия" },

  // ── Сцепление ─────────────────────────────────────────────────────────────────
  { code: "CLUTCH", name: "Замена сцепления (комплект)", normHours: 6.0, category: "Сцепление" },
  { code: "CLUTCH-DISC", name: "Замена диска сцепления", normHours: 6.0, category: "Сцепление" },
  { code: "CLUTCH-CYL", name: "Замена главного цилиндра сцепления", normHours: 1.5, category: "Сцепление" },
  { code: "CLUTCH-SLAVE", name: "Замена рабочего цилиндра сцепления", normHours: 1.0, category: "Сцепление" },
  { code: "CLUTCH-CABLE", name: "Замена троса сцепления", normHours: 1.5, category: "Сцепление" },
  { code: "CLUTCH-BLEED", name: "Прокачка сцепления (гидро)", normHours: 0.5, category: "Сцепление" },

  // ── Шиномонтаж ────────────────────────────────────────────────────────────────
  { code: "TIRE-1", name: "Шиномонтаж 1 колеса", normHours: 0.2, category: "Шиномонтаж" },
  { code: "TIRE-4", name: "Шиномонтаж 4 колеса", normHours: 0.8, category: "Шиномонтаж" },
  { code: "TIRE-BAL-1", name: "Балансировка 1 колеса", normHours: 0.2, category: "Шиномонтаж" },
  { code: "TIRE-BAL-4", name: "Балансировка 4 колёс", normHours: 0.8, category: "Шиномонтаж" },
  { code: "TIRE-SEASON", name: "Сезонная переобувка (4 колеса)", normHours: 1.0, category: "Шиномонтаж" },
  { code: "TIRE-STORE", name: "Сезонное хранение шин (монтаж)", normHours: 0.3, category: "Шиномонтаж" },
  { code: "TIRE-TPMS", name: "Программирование датчика TPMS", normHours: 0.5, category: "Шиномонтаж" },
  { code: "TIRE-REPAIR", name: "Ремонт прокола (грибок / жгут)", normHours: 0.4, category: "Шиномонтаж" },
  { code: "TIRE-RUNFLAT", name: "Шиномонтаж RunFlat (1 колесо)", normHours: 0.5, category: "Шиномонтаж" },
  { code: "WHEEL-ALIGN", name: "Развал-схождение (2 оси)", normHours: 1.0, category: "Шиномонтаж" },
  { code: "WHEEL-ALIGN-1", name: "Развал-схождение (передняя ось)", normHours: 0.8, category: "Шиномонтаж" },
  { code: "WHEEL-ALIGN-3D", name: "3D развал-схождение", normHours: 1.2, category: "Шиномонтаж" },
  { code: "WHEEL-TORQUE", name: "Проверка момента затяжки колёс", normHours: 0.2, category: "Шиномонтаж" },

  // ── Климат ────────────────────────────────────────────────────────────────────
  { code: "AC-FILL", name: "Заправка кондиционера", normHours: 1.0, category: "Климат" },
  { code: "AC-LEAK", name: "Поиск утечки кондиционера", normHours: 1.5, category: "Климат" },
  { code: "AC-COMP", name: "Замена компрессора кондиционера", normHours: 3.0, category: "Климат" },
  { code: "AC-COND", name: "Замена конденсора кондиционера", normHours: 2.5, category: "Климат" },
  { code: "AC-EVAP", name: "Замена испарителя кондиционера", normHours: 8.0, category: "Климат" },
  { code: "AC-DRIER", name: "Замена осушителя / ресивера", normHours: 1.5, category: "Климат" },
  { code: "AC-VALVE", name: "Замена ТРВ / расширительного клапана", normHours: 2.0, category: "Климат" },
  { code: "AC-DISINF", name: "Антибактериальная обработка кондиционера", normHours: 0.5, category: "Климат" },
  { code: "HEAT-VALVE", name: "Замена крана печки", normHours: 2.0, category: "Климат" },
  { code: "HEAT-MOTOR", name: "Замена мотора отопителя", normHours: 3.0, category: "Климат" },
  { code: "HEAT-FLAPS", name: "Ремонт заслонок печки", normHours: 4.0, category: "Климат" },

  // ── Электрика ─────────────────────────────────────────────────────────────────
  { code: "ELEC-BATT", name: "Замена АКБ", normHours: 0.3, category: "Электрика" },
  { code: "ELEC-BATT-REG", name: "Регистрация АКБ (Start-Stop)", normHours: 0.5, category: "Электрика" },
  { code: "ELEC-ALT", name: "Замена генератора", normHours: 2.0, category: "Электрика" },
  { code: "ELEC-START", name: "Замена стартера", normHours: 2.5, category: "Электрика" },
  { code: "ELEC-START-REP", name: "Ремонт стартера", normHours: 3.0, category: "Электрика" },
  { code: "ELEC-ALT-REP", name: "Ремонт генератора", normHours: 3.0, category: "Электрика" },
  { code: "ELEC-LAMP", name: "Замена лампы (1 шт.)", normHours: 0.2, category: "Электрика" },
  { code: "ELEC-LAMP-LED", name: "Установка LED ламп (комплект)", normHours: 0.5, category: "Электрика" },
  { code: "ELEC-HORN", name: "Замена звукового сигнала", normHours: 0.5, category: "Электрика" },
  { code: "ELEC-WIN-M", name: "Замена мотора стеклоподъёмника", normHours: 2.0, category: "Электрика" },
  { code: "ELEC-LOCK", name: "Замена замка двери / актуатора", normHours: 2.0, category: "Электрика" },
  { code: "ELEC-SENSOR-O2", name: "Замена кислородного датчика (лямбда)", normHours: 0.8, category: "Электрика" },
  { code: "ELEC-SENSOR-MAF", name: "Замена ДМРВ", normHours: 0.5, category: "Электрика" },
  { code: "ELEC-SENSOR-CKP", name: "Замена датчика коленвала", normHours: 1.0, category: "Электрика" },
  { code: "ELEC-SENSOR-CMP", name: "Замена датчика распредвала", normHours: 1.0, category: "Электрика" },
  { code: "ELEC-SENSOR-ABS", name: "Замена датчика ABS", normHours: 1.0, category: "Электрика" },
  { code: "ELEC-SENSOR-PARK", name: "Замена датчика парковки", normHours: 0.8, category: "Электрика" },
  { code: "ELEC-RELAY", name: "Замена реле", normHours: 0.3, category: "Электрика" },
  { code: "ELEC-FUSE", name: "Диагностика / замена предохранителей", normHours: 0.5, category: "Электрика" },
  { code: "ELEC-WIRE-REP", name: "Ремонт проводки", normHours: 2.0, category: "Электрика" },
  { code: "ELEC-ALARM", name: "Установка сигнализации", normHours: 3.0, category: "Электрика" },
  { code: "ELEC-REMOTE", name: "Установка автозапуска", normHours: 4.0, category: "Электрика" },
  { code: "ELEC-CAMERA", name: "Установка камеры заднего вида", normHours: 2.0, category: "Электрика" },
  { code: "ELEC-PARKTRON", name: "Установка парктроников", normHours: 2.5, category: "Электрика" },

  // ── Выхлоп ────────────────────────────────────────────────────────────────────
  { code: "EXH-MUFF", name: "Замена глушителя", normHours: 1.5, category: "Выхлоп" },
  { code: "EXH-RES", name: "Замена резонатора", normHours: 1.5, category: "Выхлоп" },
  { code: "EXH-CAT", name: "Замена катализатора", normHours: 2.0, category: "Выхлоп" },
  { code: "EXH-CAT-DEL", name: "Удаление катализатора + прошивка", normHours: 3.0, category: "Выхлоп" },
  { code: "EXH-FLEX", name: "Замена гофры глушителя", normHours: 2.0, category: "Выхлоп" },
  { code: "EXH-MANIF", name: "Замена выпускного коллектора", normHours: 4.0, category: "Выхлоп" },
  { code: "EXH-SEAL", name: "Замена прокладки приёмной трубы", normHours: 1.5, category: "Выхлоп" },
  { code: "EXH-WELD", name: "Сварка выхлопной системы", normHours: 1.5, category: "Выхлоп" },

  // ── Топливная система ─────────────────────────────────────────────────────────
  { code: "FUEL-PUMP", name: "Замена бензонасоса (модуль в баке)", normHours: 3.0, category: "Топливная" },
  { code: "FUEL-FILT", name: "Замена топливного фильтра", normHours: 0.8, category: "Топливная" },
  { code: "FUEL-RAIL", name: "Замена топливной рампы", normHours: 2.0, category: "Топливная" },
  { code: "FUEL-REG", name: "Замена регулятора давления топлива", normHours: 1.5, category: "Топливная" },
  { code: "FUEL-TANK", name: "Снятие / установка топливного бака", normHours: 4.0, category: "Топливная" },
  { code: "FUEL-LINE", name: "Замена топливной магистрали", normHours: 2.0, category: "Топливная" },
  { code: "FUEL-CLEAN", name: "Промывка топливной системы", normHours: 1.0, category: "Топливная" },
  { code: "GAS-LPG-SERV", name: "ТО газового оборудования (ГБО)", normHours: 1.5, category: "Топливная" },
  { code: "GAS-LPG-DIAG", name: "Диагностика ГБО", normHours: 1.0, category: "Топливная" },

  // ── Кузов ─────────────────────────────────────────────────────────────────────
  { code: "BODY-LIGHT", name: "Замена фары / лампы", normHours: 0.5, category: "Кузов" },
  { code: "BODY-LIGHT-ASSY", name: "Замена фары в сборе", normHours: 1.0, category: "Кузов" },
  { code: "BODY-GLASS-W", name: "Замена лобового стекла", normHours: 2.0, category: "Кузов" },
  { code: "BODY-GLASS-R", name: "Замена заднего стекла", normHours: 2.5, category: "Кузов" },
  { code: "BODY-GLASS-S", name: "Замена бокового стекла", normHours: 1.5, category: "Кузов" },
  { code: "BODY-MIRROR", name: "Замена зеркала бокового", normHours: 0.8, category: "Кузов" },
  { code: "BODY-HANDLE", name: "Замена ручки двери", normHours: 1.0, category: "Кузов" },
  { code: "BODY-HINGE", name: "Регулировка / замена петель двери", normHours: 1.5, category: "Кузов" },
  { code: "BODY-BUMPER-F", name: "Снятие / установка переднего бампера", normHours: 1.5, category: "Кузов" },
  { code: "BODY-BUMPER-R", name: "Снятие / установка заднего бампера", normHours: 1.5, category: "Кузов" },
  { code: "BODY-FENDER", name: "Снятие / установка крыла", normHours: 2.0, category: "Кузов" },
  { code: "BODY-HOOD", name: "Регулировка капота", normHours: 0.8, category: "Кузов" },
  { code: "BODY-TRUNK", name: "Регулировка багажника / крышки", normHours: 0.8, category: "Кузов" },
  { code: "BODY-SILL", name: "Замена порога", normHours: 6.0, category: "Кузов" },
  { code: "BODY-PANEL", name: "Замена кузовной панели", normHours: 8.0, category: "Кузов" },
  { code: "BODY-PAINT-LOC", name: "Локальная покраска", normHours: 4.0, category: "Кузов" },
  { code: "BODY-PAINT-FULL", name: "Полная покраска", normHours: 40.0, category: "Кузов" },
  { code: "BODY-DENT", name: "Удаление вмятины без покраски (PDR)", normHours: 2.0, category: "Кузов" },
  { code: "BODY-POLISH", name: "Полировка кузова", normHours: 3.0, category: "Кузов" },
  { code: "BODY-ANTICOR", name: "Антикоррозийная обработка", normHours: 4.0, category: "Кузов" },
  { code: "BODY-SOUND", name: "Шумоизоляция салона / арок", normHours: 6.0, category: "Кузов" },
  { code: "BODY-TINT", name: "Тонировка стёкол", normHours: 2.0, category: "Кузов" },
  { code: "BODY-FILM", name: "Оклейка плёнкой (элемент)", normHours: 3.0, category: "Кузов" },

  // ── Салон ─────────────────────────────────────────────────────────────────────
  { code: "INT-SEAT", name: "Снятие / установка сиденья", normHours: 0.8, category: "Салон" },
  { code: "INT-BELT", name: "Замена ремня безопасности", normHours: 1.5, category: "Салон" },
  { code: "INT-DASH", name: "Снятие / установка торпедо", normHours: 8.0, category: "Салон" },
  { code: "INT-AIRBAG", name: "Замена подушки безопасности", normHours: 2.0, category: "Салон" },
  { code: "INT-STEER-W", name: "Замена рулевого колеса", normHours: 0.5, category: "Салон" },
  { code: "INT-CLEAN", name: "Химчистка салона", normHours: 4.0, category: "Салон" },
  { code: "INT-ODOR", name: "Устранение запаха в салоне (озон)", normHours: 1.0, category: "Салон" },

  // ── Детейлинг ─────────────────────────────────────────────────────────────────
  { code: "DET-WASH", name: "Комплексная мойка", normHours: 1.0, category: "Детейлинг" },
  { code: "DET-WAX", name: "Нанесение воска / керамики", normHours: 2.0, category: "Детейлинг" },
  { code: "DET-ENGINE", name: "Мойка двигателя", normHours: 1.0, category: "Детейлинг" },
  { code: "DET-DRY", name: "Сухая мойка", normHours: 1.5, category: "Детейлинг" },

  // ── Прочее / слесарка ─────────────────────────────────────────────────────────
  { code: "MISC-NUT", name: "Снятие прикипевшей гайки / болта", normHours: 0.5, category: "Слесарка" },
  { code: "MISC-WELD", name: "Сварочные работы (слесарка)", normHours: 2.0, category: "Слесарка" },
  { code: "MISC-TOW-PREP", name: "Подготовка к эвакуации", normHours: 0.5, category: "Слесарка" },
  { code: "MISC-KEY", name: "Изготовление / привязка ключа", normHours: 1.5, category: "Слесарка" },
  { code: "MISC-RECYCLE", name: "Утилизация отработанных жидкостей", normHours: 0.3, category: "Слесарка" },
  { code: "MISC-INSPECT-GAI", name: "Подготовка к техосмотру", normHours: 1.0, category: "Слесарка" },
  { code: "MISC-HOURLY", name: "Слесарные работы (нормо-час)", normHours: 1.0, category: "Слесарка" },
];
